import { describe, expect, it } from "vitest";
import { isRendererToolName } from "./api";
import { toolCallPresentation } from "./ToolCallCard";
import contract from "./renderer-tool-names.json";

/**
 * The tool vocabulary as the server actually serializes it.
 *
 * Four hand-written tables key off this list — the TS union, its runtime guard,
 * the copy table, and the icon table — and until this file existed nothing
 * connected them to the Rust enum they mirror. Three tools shipped missing an
 * entry in one table or another (`list_folder`, `import_connected_file`, and
 * `exec`'s historical title), each found by reading rather than by failing.
 *
 * Generated by a Rust test, checked in, and verified on both sides. The check is
 * the guarantee, not the generation: CI fails if the file is stale, and these
 * tests fail if the renderer has drifted from it.
 */
const CONTRACT: { tools: string[] } = contract;

describe("renderer tool-name contract", () => {
  it("has a vocabulary to check against", () => {
    expect(CONTRACT.tools.length).toBeGreaterThan(0);
    expect(CONTRACT.tools).toContain("other");
  });

  it("accepts exactly the names the server can send", () => {
    for (const name of CONTRACT.tools) {
      expect(isRendererToolName(name), `${name} is missing from the union`).toBe(
        true,
      );
    }
  });

  it("rejects anything the server cannot send", () => {
    // The union is an allowlist, so a name the server folds must not sneak
    // through the guard and become a display path for a provider string.
    for (const name of [
      "mcp__vendor__exfiltrate",
      "historical_unknown_tool",
      "",
      "SEARCH",
    ]) {
      expect(isRendererToolName(name), `${name} should not be accepted`).toBe(
        false,
      );
    }
  });

  it("gives every name its own copy, except the deliberate fold", () => {
    for (const name of CONTRACT.tools) {
      const presentation = toolCallPresentation(name, "running");
      if (name === "other") {
        // `other` is the server's fold for anything unrecognized, so the
        // generic wording is the correct answer rather than a missing entry.
        expect(presentation.label).toBe("Use a tool");
        continue;
      }
      expect(presentation.label, `${name} has no copy of its own`).not.toBe(
        "Use a tool",
      );
    }
  });
});
