[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/brightwave-inc/openwave"
homepage = "https://github.com/brightwave-inc/openwave"
authors = ["Brightwave, Inc."]

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
