/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        "page-background": "var(--page-background)",
        border: "var(--border)",
        muted: "var(--muted)",
        "muted-foreground": "var(--muted-foreground)",
        primary: "var(--primary)",
        "primary-foreground": "var(--primary-foreground)",
        critical: "var(--critical)",
        "critical-foreground": "var(--critical-foreground)",
        "critical-background": "var(--critical-background)",
        "critical-border": "var(--critical-border)",
        success: "var(--success)",
        "success-foreground": "var(--success-foreground)",
        "success-background": "var(--success-background)",
        "success-border": "var(--success-border)",
        info: "var(--info)",
        "info-foreground": "var(--info-foreground)",
        "info-background": "var(--info-background)",
        "info-border": "var(--info-border)",
        warning: "var(--warning)",
        "warning-foreground": "var(--warning-foreground)",
        "warning-background": "var(--warning-background)",
        "warning-border": "var(--warning-border)",
        live: "var(--live)",
        "live-foreground": "var(--live-foreground)",
        "live-background": "var(--live-background)",
        "live-border": "var(--live-border)",
      },
    },
  },
  plugins: [],
};
