#!/usr/bin/env python3
"""Create, renumber, and verify Tidebreak architecture decision records.

Numbers are unique. Gaps are allowed. Two branches that each take the next
number both append to docs/decisions/manifest.txt, so Git requires a person
to resolve the collision before either branch can merge.
"""

from __future__ import annotations

import argparse
import datetime as dt
import difflib
import re
import subprocess
import sys
import unicodedata
from dataclasses import dataclass
from pathlib import Path


STATUSES = ("Proposed", "Accepted", "Superseded", "Rejected")
ADR_NAME = re.compile(r"^(?P<number>\d{4})-(?P<slug>[a-z0-9]+(?:-[a-z0-9]+)*)\.md$")
NUMBER_HEADING = re.compile(r"^# (?P<number>\d+)\. (?P<title>.+)$")
TEMPLATE_HEADING = "# N. Decision Title"

MANIFEST_HEADER = """# ADR numbering manifest. Generated by `python3 scripts/adr.py sync`.
#
# Every ADR in docs/decisions and the number it holds. The data is redundant:
# the decision files are the readable authority. This file exists so two
# branches which each add the next ADR append at the same place and Git
# requires a person to resolve the collision before either branch can merge.
#
# A conflict here means another branch took the same number. Keep the ADR from
# main, renumber the unmerged ADR with `python3 scripts/adr.py renumber …`,
# then rerun `python3 scripts/adr.py check`. Do not hand-edit this file.
"""


class AdrError(Exception):
    """A user-facing ADR contract failure."""


@dataclass(frozen=True)
class Adr:
    number: int
    filename: str
    path: Path
    title: str
    date: str
    status: str

    @property
    def label(self) -> str:
        return f"{self.number:04d}"


def repository_root(argument: str | None) -> Path:
    if argument:
        return Path(argument).resolve()
    return Path(__file__).resolve().parent.parent


def decisions_directory(root: Path) -> Path:
    return root / "docs" / "decisions"


def read_metadata(path: Path, number: int) -> tuple[str, str, str]:
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    if not lines:
        raise AdrError(f"{path.name}: file is empty")

    heading = NUMBER_HEADING.fullmatch(lines[0])
    if not heading:
        raise AdrError(f"{path.name}: first line must be '# N. Title'")
    heading_number = int(heading.group("number"))
    if heading_number != number:
        raise AdrError(
            f"{path.name}: heading says {heading_number}, filename says {number:04d}"
        )
    title = heading.group("title").strip()

    status_match = re.search(
        rf"(?m)^- Status:[ \t]+({'|'.join(STATUSES)})\b",
        text,
    )
    if not status_match:
        raise AdrError(
            f"{path.name}: status must start with one of {', '.join(STATUSES)}"
        )
    status = status_match.group(1)

    date_match = re.search(
        r"(?m)^- Date:[ \t]+(\d{4}-\d{2}-\d{2})(?:[ \t]|$)",
        text,
    )
    if not date_match:
        raise AdrError(f"{path.name}: missing Date: YYYY-MM-DD metadata")
    date = date_match.group(1)
    try:
        dt.date.fromisoformat(date)
    except ValueError as error:
        raise AdrError(f"{path.name}: invalid date {date}") from error

    return title, date, status


def load_adrs(root: Path, *, allow_duplicate_numbers: bool = False) -> list[Adr]:
    directory = decisions_directory(root)
    if not directory.is_dir():
        raise AdrError(f"{directory}: decision directory does not exist")

    adrs: list[Adr] = []
    for path in sorted(directory.glob("*.md")):
        if path.name == "README.md":
            continue
        match = ADR_NAME.fullmatch(path.name)
        if not match:
            raise AdrError(f"{path.name}: ADR filenames must match NNNN-slug.md")
        number = int(match.group("number"))
        if number == 0:
            if path.name != "0000-template.md":
                raise AdrError("ADR 0000 is reserved for 0000-template.md")
            if path.read_text(encoding="utf-8").splitlines()[:1] != [TEMPLATE_HEADING]:
                raise AdrError("0000-template.md must start with '# N. Decision Title'")
            adrs.append(
                Adr(
                    number=0,
                    filename=path.name,
                    path=path,
                    title="Decision title",
                    date="—",
                    status="Template",
                )
            )
            continue
        title, date, status = read_metadata(path, number)
        adrs.append(
            Adr(
                number=number,
                filename=path.name,
                path=path,
                title=title,
                date=date,
                status=status,
            )
        )

    if not adrs:
        raise AdrError(f"{directory}: no ADRs found")
    templates = [adr for adr in adrs if adr.number == 0]
    if len(templates) != 1:
        raise AdrError("docs/decisions must contain exactly one 0000-template.md")

    by_number: dict[int, list[str]] = {}
    for adr in adrs:
        by_number.setdefault(adr.number, []).append(adr.filename)
    duplicates = {
        number: names for number, names in by_number.items() if len(names) > 1
    }
    if duplicates and not allow_duplicate_numbers:
        details = "; ".join(
            f"{number:04d}: {', '.join(names)}"
            for number, names in sorted(duplicates.items())
        )
        raise AdrError(f"ADR numbers are duplicated: {details}")

    numbered = [adr for adr in adrs if adr.number > 0]
    if not numbered:
        raise AdrError("docs/decisions contains no numbered decisions")

    return sorted(adrs, key=lambda adr: (adr.number, adr.filename))


def render_manifest(adrs: list[Adr]) -> str:
    rows = "".join(f"{adr.label}  {adr.filename}\n" for adr in adrs)
    return MANIFEST_HEADER + rows


def synchronize(root: Path, adrs: list[Adr] | None = None) -> None:
    adrs = adrs or load_adrs(root)
    manifest_path = decisions_directory(root) / "manifest.txt"
    manifest_path.write_text(render_manifest(adrs), encoding="utf-8")
    print(f"ADR manifest: wrote {len(adrs) - 1} decisions to docs/decisions/manifest.txt")


def difference(expected: str, actual: str, expected_name: str, actual_name: str) -> str:
    return "".join(
        difflib.unified_diff(
            actual.splitlines(keepends=True),
            expected.splitlines(keepends=True),
            fromfile=actual_name,
            tofile=expected_name,
        )
    )


def base_drift_errors(root: Path, adrs: list[Adr], base: str) -> list[str]:
    command = [
        "git",
        "-C",
        str(root),
        "ls-tree",
        "--name-only",
        f"{base}:docs/decisions",
    ]
    try:
        result = subprocess.run(command, check=False, capture_output=True, text=True)
    except FileNotFoundError:
        print(
            f"ADR numbering: git is unavailable; skipping comparison with {base}",
            file=sys.stderr,
        )
        return []
    if result.returncode != 0:
        print(
            f"ADR numbering: cannot read {base}:docs/decisions; skipping offline comparison",
            file=sys.stderr,
        )
        return []

    base_by_number: dict[int, str] = {}
    for filename in result.stdout.splitlines():
        match = ADR_NAME.fullmatch(filename)
        if match and match.group("number") != "0000":
            base_by_number[int(match.group("number"))] = filename
    local_by_number = {adr.number: adr.filename for adr in adrs if adr.number > 0}
    return [
        f"number {number:04d} is {base_filename} on {base} but {local_by_number[number]} here"
        for number, base_filename in sorted(base_by_number.items())
        if number in local_by_number and local_by_number[number] != base_filename
    ]


def check(root: Path, base: str | None) -> None:
    adrs = load_adrs(root)
    manifest_path = decisions_directory(root) / "manifest.txt"
    errors: list[str] = []

    expected_manifest = render_manifest(adrs)
    actual_manifest = (
        manifest_path.read_text(encoding="utf-8") if manifest_path.exists() else ""
    )
    if actual_manifest != expected_manifest:
        errors.append(
            "ADR manifest is stale; run `python3 scripts/adr.py sync`\n"
            + difference(
                expected_manifest,
                actual_manifest,
                "generated manifest",
                "docs/decisions/manifest.txt",
            )
        )

    if base:
        errors.extend(base_drift_errors(root, adrs, base))

    if errors:
        for error in errors:
            print(f"ADR check: {error}", file=sys.stderr)
        raise AdrError(f"{len(errors)} ADR contract failure(s)")
    numbered = [adr for adr in adrs if adr.number > 0]
    suffix = f" and clear of {base}" if base else ""
    print(
        f"ADR check: {len(numbered)} decisions, "
        f"{numbered[0].label} through {numbered[-1].label}, "
        f"manifest synchronized{suffix}"
    )


def slugify(title: str) -> str:
    normalized = unicodedata.normalize("NFKD", title).encode("ascii", "ignore").decode()
    slug = re.sub(r"[^a-z0-9]+", "-", normalized.lower()).strip("-")
    if not slug:
        raise AdrError("title does not contain any characters usable in a filename")
    return slug


def create_adr(
    root: Path,
    title: str,
    slug: str | None,
    owners: str,
    date: str,
    supersedes: str,
) -> None:
    adrs = load_adrs(root)
    try:
        dt.date.fromisoformat(date)
    except ValueError as error:
        raise AdrError(f"invalid ADR date {date}; expected YYYY-MM-DD") from error
    filename_slug = slug or slugify(title)
    if not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", filename_slug):
        raise AdrError("slug must contain lowercase letters, numbers, and single hyphens")
    number = max(adr.number for adr in adrs) + 1
    if number > 9999:
        raise AdrError("ADR numbering exhausted four digits")
    target = decisions_directory(root) / f"{number:04d}-{filename_slug}.md"
    if target.exists():
        raise AdrError(f"{target.name} already exists")

    template = (decisions_directory(root) / "0000-template.md").read_text(encoding="utf-8")
    replacements = {
        TEMPLATE_HEADING: f"# {number}. {title}",
        "- Status: Proposed | Accepted | Superseded | Rejected": "- Status: Proposed",
        "- Date: YYYY-MM-DD": f"- Date: {date}",
        "- Owners: name or area": f"- Owners: {owners}",
        "- Supersedes: record number, if any": f"- Supersedes: {supersedes}",
    }
    for old, new in replacements.items():
        if old not in template:
            raise AdrError(f"0000-template.md is missing expected text: {old}")
        template = template.replace(old, new, 1)
    target.write_text(template, encoding="utf-8")
    synchronize(root)
    print(f"ADR new: created {target.relative_to(root)}")


def resolve_selector(adrs: list[Adr], selector: str) -> Adr:
    normalized = Path(selector).name
    candidates = [
        adr
        for adr in adrs
        if adr.number > 0
        and (
            normalized == adr.filename
            or normalized == adr.path.stem
            or selector == adr.label
        )
    ]
    if not candidates:
        raise AdrError(f"cannot find ADR matching {selector}")
    if len(candidates) > 1:
        raise AdrError(
            f"{selector} matches multiple ADRs; pass the full filename of the draft to renumber"
        )
    return candidates[0]


def replace_adr_links(root: Path, old: Adr, new_filename: str) -> None:
    for path in sorted((root / "docs").rglob("*.md")):
        text = path.read_text(encoding="utf-8")
        updated = text.replace(old.filename, new_filename)
        if updated != text:
            path.write_text(updated, encoding="utf-8")


def renumber_adr(root: Path, selector: str, requested_number: str | None) -> None:
    adrs = load_adrs(root, allow_duplicate_numbers=True)
    source = resolve_selector(adrs, selector)
    occupied = {adr.number for adr in adrs if adr.number > 0 and adr.path != source.path}
    if requested_number:
        if not re.fullmatch(r"\d{1,4}", requested_number):
            raise AdrError("NUMBER must be one to four decimal digits")
        number = int(requested_number)
    else:
        number = max(adr.number for adr in adrs) + 1
    if number <= 0 or number > 9999:
        raise AdrError("ADR number must be between 0001 and 9999")
    if number in occupied:
        colliding = next(
            adr.filename
            for adr in adrs
            if adr.number == number and adr.path != source.path
        )
        raise AdrError(f"ADR {number:04d} is already used by {colliding}")
    if number == source.number:
        raise AdrError(f"{source.filename} is already numbered {number:04d}")

    new_filename = f"{number:04d}" + source.filename[4:]
    target = source.path.with_name(new_filename)
    text = source.path.read_text(encoding="utf-8")
    lines = text.splitlines(keepends=True)
    heading = lines[0].rstrip("\n")
    newline = "\n" if lines[0].endswith("\n") else ""
    if not NUMBER_HEADING.fullmatch(heading):
        raise AdrError(f"{source.filename}: cannot rewrite unrecognized heading")
    lines[0] = re.sub(r"^# \d+\.", f"# {number}.", heading) + newline
    source.path.write_text("".join(lines), encoding="utf-8")
    source.path.rename(target)
    replace_adr_links(root, source, new_filename)
    # Other collisions may still be in the tree while this one is being fixed.
    synchronize(root, load_adrs(root, allow_duplicate_numbers=True))
    print(f"ADR renumber: {source.filename} -> {new_filename}")


def parser() -> argparse.ArgumentParser:
    result = argparse.ArgumentParser(description=__doc__)
    result.add_argument("--root", help=argparse.SUPPRESS)
    subcommands = result.add_subparsers(dest="command", required=True)
    subcommands.add_parser("sync", help="regenerate the numbering manifest")
    check_parser = subcommands.add_parser(
        "check", help="verify unique numbers and a current manifest"
    )
    check_parser.add_argument(
        "--base", help="also reject numbers used by a different ADR on this ref"
    )
    new_parser = subcommands.add_parser(
        "new", help="create the next proposed ADR from the template"
    )
    new_parser.add_argument("--title", required=True)
    new_parser.add_argument("--slug")
    new_parser.add_argument("--owners", default="core")
    new_parser.add_argument("--date", default=dt.date.today().isoformat())
    new_parser.add_argument("--supersedes", default="none")
    renumber_parser = subcommands.add_parser(
        "renumber", help="move an ADR to a free number"
    )
    renumber_parser.add_argument("adr", help="ADR number, stem, filename, or path")
    renumber_parser.add_argument(
        "--number", help="target number; defaults to one past the highest"
    )
    return result


def main() -> int:
    arguments = parser().parse_args()
    root = repository_root(arguments.root)
    try:
        if arguments.command == "sync":
            synchronize(root)
        elif arguments.command == "check":
            check(root, arguments.base)
        elif arguments.command == "new":
            create_adr(
                root,
                arguments.title,
                arguments.slug,
                arguments.owners,
                arguments.date,
                arguments.supersedes,
            )
        elif arguments.command == "renumber":
            renumber_adr(root, arguments.adr, arguments.number)
        else:
            raise AssertionError(arguments.command)
    except AdrError as error:
        print(f"ADR: {error}", file=sys.stderr)
        return 65
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
