//! Turn-run scheduling tables of the schema baseline.

use sea_orm_migration::prelude::*;

use crate::db::migration::idens::*;
use crate::model::{TurnClientWaitStatus, TurnRunStatus, TurnSteerStatus};

/// The advisory locks that serialize the claim paths against each other.
///
/// One row per lock name, seeded by [`super::SEED_STATEMENTS`]. Taking a lock
/// is a no-op `UPDATE` of its row, so the row's *existence* is what serializes
/// workers — a missing row is a hard error rather than an unserialized path.
pub(super) fn advisory_lock_table() -> TableCreateStatement {
    Table::create()
        .table(AdvisoryLock::Table)
        .col(
            ColumnDef::new(AdvisoryLock::Name)
                .string_len(64)
                .not_null()
                .primary_key(),
        )
        .to_owned()
}

pub(super) fn advisory_lock_indexes() -> Vec<IndexCreateStatement> {
    vec![]
}

pub(super) fn turn_claim_table() -> TableCreateStatement {
    Table::create()
        .table(TurnClaim::Table)
        .col(
            ColumnDef::new(TurnClaim::Token)
                .uuid()
                .not_null()
                .primary_key(),
        )
        .col(ColumnDef::new(TurnClaim::TurnId).uuid().not_null())
        .col(ColumnDef::new(TurnClaim::AttemptCount).integer().not_null())
        .col(ColumnDef::new(TurnClaim::ClaimCount).integer().not_null())
        .col(
            ColumnDef::new(TurnClaim::ClaimedAt)
                .timestamp_with_time_zone()
                .not_null(),
        )
        .col(
            ColumnDef::new(TurnClaim::LeaseExpiresAt)
                .timestamp_with_time_zone()
                .not_null(),
        )
        .check(Expr::col(TurnClaim::AttemptCount).gte(1))
        .check(Expr::col(TurnClaim::ClaimCount).gte(Expr::col(TurnClaim::AttemptCount)))
        .check(Expr::col(TurnClaim::LeaseExpiresAt).gt(Expr::col(TurnClaim::ClaimedAt)))
        .to_owned()
}

pub(super) fn turn_claim_indexes() -> Vec<IndexCreateStatement> {
    vec![
        Index::create()
            .name("idx_turn_claim_identity")
            .table(TurnClaim::Table)
            .col(TurnClaim::Token)
            .col(TurnClaim::TurnId)
            .col(TurnClaim::AttemptCount)
            .col(TurnClaim::ClaimCount)
            .unique()
            .to_owned(),
        // Failure receipts remain attempt-scoped even when one attempt spans
        // multiple worker lease segments.
        Index::create()
            .name("idx_turn_claim_failure_identity")
            .table(TurnClaim::Table)
            .col(TurnClaim::Token)
            .col(TurnClaim::TurnId)
            .col(TurnClaim::AttemptCount)
            .unique()
            .to_owned(),
        Index::create()
            .name("idx_turn_claim_count")
            .table(TurnClaim::Table)
            .col(TurnClaim::TurnId)
            .col(TurnClaim::ClaimCount)
            .unique()
            .to_owned(),
        Index::create()
            .name("idx_turn_claim_turn_token")
            .table(TurnClaim::Table)
            .col(TurnClaim::TurnId)
            .col(TurnClaim::Token)
            .unique()
            .to_owned(),
    ]
}

pub(super) fn turn_run_table() -> TableCreateStatement {
    let valid_turn_status = Expr::col(TurnRun::Status).is_in([
        TurnRunStatus::Queued.as_str(),
        TurnRunStatus::Running.as_str(),
        TurnRunStatus::Cancelling.as_str(),
        TurnRunStatus::WaitingForClient.as_str(),
        TurnRunStatus::WaitingForAgentRun.as_str(),
        TurnRunStatus::CancellingClient.as_str(),
        TurnRunStatus::Resuming.as_str(),
        TurnRunStatus::RetryWait.as_str(),
        TurnRunStatus::Completed.as_str(),
        TurnRunStatus::Failed.as_str(),
        TurnRunStatus::Cancelled.as_str(),
    ]);
    let active_lease = Expr::col(TurnRun::Status)
        .is_in([
            TurnRunStatus::Running.as_str(),
            TurnRunStatus::Cancelling.as_str(),
        ])
        .and(Expr::col(TurnRun::LeaseToken).is_not_null())
        .and(Expr::col(TurnRun::LeaseExpiresAt).is_not_null());
    let no_lease = Expr::col(TurnRun::Status)
        .ne(TurnRunStatus::Running.as_str())
        .and(Expr::col(TurnRun::Status).ne(TurnRunStatus::Cancelling.as_str()))
        .and(Expr::col(TurnRun::LeaseToken).is_null())
        .and(Expr::col(TurnRun::LeaseExpiresAt).is_null());
    let terminal_finished = Expr::col(TurnRun::Status)
        .is_in([
            TurnRunStatus::Completed.as_str(),
            TurnRunStatus::Failed.as_str(),
            TurnRunStatus::Cancelled.as_str(),
        ])
        .and(Expr::col(TurnRun::FinishedAt).is_not_null());
    let nonterminal_unfinished = Expr::col(TurnRun::Status)
        .is_in([
            TurnRunStatus::Queued.as_str(),
            TurnRunStatus::Running.as_str(),
            TurnRunStatus::Cancelling.as_str(),
            TurnRunStatus::WaitingForClient.as_str(),
            TurnRunStatus::WaitingForAgentRun.as_str(),
            TurnRunStatus::CancellingClient.as_str(),
            TurnRunStatus::Resuming.as_str(),
            TurnRunStatus::RetryWait.as_str(),
        ])
        .and(Expr::col(TurnRun::FinishedAt).is_null());
    let queued_attempt = Expr::col(TurnRun::Status)
        .eq(TurnRunStatus::Queued.as_str())
        .and(Expr::col(TurnRun::AttemptCount).eq(0))
        .and(Expr::col(TurnRun::ClaimCount).eq(0))
        .and(Expr::col(TurnRun::StartedAt).is_null());
    let leased_attempt = Expr::col(TurnRun::Status)
        .is_in([
            TurnRunStatus::Running.as_str(),
            TurnRunStatus::Cancelling.as_str(),
        ])
        .and(Expr::col(TurnRun::AttemptCount).gte(1))
        .and(Expr::col(TurnRun::StartedAt).is_not_null());
    let retryable_attempt = Expr::col(TurnRun::Status)
        .eq(TurnRunStatus::RetryWait.as_str())
        .and(Expr::col(TurnRun::AttemptCount).gte(1))
        .and(Expr::col(TurnRun::AttemptCount).lt(Expr::col(TurnRun::MaxAttempts)))
        .and(Expr::col(TurnRun::StartedAt).is_not_null());
    let continuation_checkpoint_attempt = Expr::col(TurnRun::Status)
        .is_in([
            TurnRunStatus::WaitingForClient.as_str(),
            TurnRunStatus::WaitingForAgentRun.as_str(),
            TurnRunStatus::CancellingClient.as_str(),
            TurnRunStatus::Resuming.as_str(),
        ])
        .and(Expr::col(TurnRun::AttemptCount).gte(1))
        .and(Expr::col(TurnRun::StartedAt).is_not_null());
    let resolved_attempt = Expr::col(TurnRun::Status)
        .is_in([
            TurnRunStatus::Completed.as_str(),
            TurnRunStatus::Failed.as_str(),
        ])
        .and(Expr::col(TurnRun::AttemptCount).gte(1))
        .and(Expr::col(TurnRun::StartedAt).is_not_null());
    let cancelled_attempt = Expr::col(TurnRun::Status)
        .eq(TurnRunStatus::Cancelled.as_str())
        .and(
            Expr::col(TurnRun::AttemptCount)
                .eq(0)
                .and(Expr::col(TurnRun::ClaimCount).eq(0))
                .and(Expr::col(TurnRun::StartedAt).is_null())
                .or(Expr::col(TurnRun::AttemptCount)
                    .gte(1)
                    .and(Expr::col(TurnRun::StartedAt).is_not_null())),
        );
    let failure_has_error = Expr::col(TurnRun::Status)
        .is_in([
            TurnRunStatus::RetryWait.as_str(),
            TurnRunStatus::Failed.as_str(),
        ])
        .and(Expr::col(TurnRun::LastErrorCode).is_not_null());
    let success_has_no_error = Expr::col(TurnRun::Status)
        .is_in([
            TurnRunStatus::Queued.as_str(),
            TurnRunStatus::Running.as_str(),
            TurnRunStatus::Cancelling.as_str(),
            TurnRunStatus::WaitingForClient.as_str(),
            TurnRunStatus::WaitingForAgentRun.as_str(),
            TurnRunStatus::CancellingClient.as_str(),
            TurnRunStatus::Resuming.as_str(),
            TurnRunStatus::Completed.as_str(),
            TurnRunStatus::Cancelled.as_str(),
        ])
        .and(Expr::col(TurnRun::LastErrorCode).is_null())
        .and(Expr::col(TurnRun::LastErrorDetail).is_null());
    let coherent_steer_generation = Expr::col(TurnRun::SteerRevision)
        .eq(0)
        .and(Expr::col(TurnRun::LastSteerAppliedAt).is_null())
        .or(Expr::col(TurnRun::SteerRevision)
            .gte(1)
            .and(Expr::col(TurnRun::LastSteerAppliedAt).is_not_null()));

    Table::create()
        .table(TurnRun::Table)
        .col(ColumnDef::new(TurnRun::Id).uuid().not_null().primary_key())
        .col(ColumnDef::new(TurnRun::ChatId).uuid().not_null())
        .col(ColumnDef::new(TurnRun::AgentRunId).uuid().not_null())
        .col(
            ColumnDef::new(TurnRun::AgentRunDepth)
                .small_integer()
                .not_null()
                .default(0),
        )
        .col(ColumnDef::new(TurnRun::InputMessageId).uuid().not_null())
        .col(ColumnDef::new(TurnRun::OutputMessageId).uuid())
        .col(
            ColumnDef::new(TurnRun::Model)
                .string_len(crate::model::TurnRun::MAX_MODEL_LEN as u32)
                .not_null(),
        )
        // The skills the user named for this turn, as a JSON array of slugs.
        // Empty is the common case and the default, so an accepted turn always
        // has an honest value rather than a null standing in for "none".
        .col(
            ColumnDef::new(TurnRun::InvokedSkills)
                .json_binary()
                .not_null(),
        )
        .col(
            ColumnDef::new(TurnRun::VoiceInputUsed)
                .boolean()
                .not_null()
                .default(false),
        )
        .col(
            ColumnDef::new(TurnRun::Status)
                .string_len(32)
                .not_null()
                .default(TurnRunStatus::Queued.as_str()),
        )
        .col(
            ColumnDef::new(TurnRun::AttemptCount)
                .integer()
                .not_null()
                .default(0),
        )
        .col(
            ColumnDef::new(TurnRun::MaxAttempts)
                .integer()
                .not_null()
                .default(crate::model::TurnRun::DEFAULT_MAX_ATTEMPTS),
        )
        .col(
            ColumnDef::new(TurnRun::ClaimCount)
                .integer()
                .not_null()
                .default(0),
        )
        .col(
            ColumnDef::new(TurnRun::ModelSteps)
                .integer()
                .not_null()
                .default(0),
        )
        .col(
            ColumnDef::new(TurnRun::InputTokens)
                .big_integer()
                .not_null()
                .default(0),
        )
        .col(
            ColumnDef::new(TurnRun::OutputTokens)
                .big_integer()
                .not_null()
                .default(0),
        )
        .col(
            ColumnDef::new(TurnRun::CacheReadInputTokens)
                .big_integer()
                .not_null()
                .default(0),
        )
        .col(
            ColumnDef::new(TurnRun::CacheCreationInputTokens)
                .big_integer()
                .not_null()
                .default(0),
        )
        .col(
            ColumnDef::new(TurnRun::AvailableAt)
                .timestamp_with_time_zone()
                .not_null(),
        )
        .col(ColumnDef::new(TurnRun::LeaseToken).uuid())
        .col(ColumnDef::new(TurnRun::LeaseExpiresAt).timestamp_with_time_zone())
        .col(ColumnDef::new(TurnRun::StartedAt).timestamp_with_time_zone())
        .col(ColumnDef::new(TurnRun::FinishedAt).timestamp_with_time_zone())
        .col(
            ColumnDef::new(TurnRun::LastErrorCode)
                .string_len(crate::model::TurnRun::MAX_ERROR_CODE_LEN as u32),
        )
        .col(
            ColumnDef::new(TurnRun::LastErrorDetail)
                .string_len(crate::model::TurnRun::MAX_ERROR_DETAIL_LEN as u32),
        )
        .col(
            ColumnDef::new(TurnRun::SteerRevision)
                .big_integer()
                .not_null()
                .default(0),
        )
        .col(ColumnDef::new(TurnRun::LastSteerAppliedAt).timestamp_with_time_zone())
        .col(
            ColumnDef::new(TurnRun::CreatedAt)
                .timestamp_with_time_zone()
                .not_null(),
        )
        .col(
            ColumnDef::new(TurnRun::UpdatedAt)
                .timestamp_with_time_zone()
                .not_null(),
        )
        .foreign_key(
            ForeignKey::create()
                .name("fk_turn_run_chat")
                .from(TurnRun::Table, TurnRun::ChatId)
                .to(Chat::Table, Chat::Id)
                .on_delete(ForeignKeyAction::Cascade),
        )
        .foreign_key(
            ForeignKey::create()
                .name("fk_turn_run_foreground_agent")
                .from_tbl(TurnRun::Table)
                .from_col(TurnRun::AgentRunId)
                .from_col(TurnRun::ChatId)
                .from_col(TurnRun::AgentRunDepth)
                .to_tbl(AgentRun::Table)
                .to_col(AgentRun::Id)
                .to_col(AgentRun::ChatId)
                .to_col(AgentRun::Depth)
                .on_delete(ForeignKeyAction::Restrict),
        )
        .foreign_key(
            ForeignKey::create()
                .name("fk_turn_run_input_message")
                .from_tbl(TurnRun::Table)
                .from_col(TurnRun::InputMessageId)
                .from_col(TurnRun::ChatId)
                .from_col(TurnRun::Id)
                .to_tbl(Message::Table)
                .to_col(Message::Id)
                .to_col(Message::ChatId)
                .to_col(Message::TurnId)
                .on_delete(ForeignKeyAction::Restrict),
        )
        .foreign_key(
            ForeignKey::create()
                .name("fk_turn_run_output_message")
                .from_tbl(TurnRun::Table)
                .from_col(TurnRun::OutputMessageId)
                .from_col(TurnRun::ChatId)
                .from_col(TurnRun::Id)
                .to_tbl(Message::Table)
                .to_col(Message::Id)
                .to_col(Message::ChatId)
                .to_col(Message::TurnId)
                .on_delete(ForeignKeyAction::Restrict),
        )
        .foreign_key(
            ForeignKey::create()
                .name("fk_turn_run_live_claim")
                .from_tbl(TurnRun::Table)
                .from_col(TurnRun::LeaseToken)
                .from_col(TurnRun::Id)
                .from_col(TurnRun::AttemptCount)
                .from_col(TurnRun::ClaimCount)
                .to_tbl(TurnClaim::Table)
                .to_col(TurnClaim::Token)
                .to_col(TurnClaim::TurnId)
                .to_col(TurnClaim::AttemptCount)
                .to_col(TurnClaim::ClaimCount)
                .on_delete(ForeignKeyAction::Restrict),
        )
        .check(
            Func::char_length(Expr::col(TurnRun::Model))
                .between(1, crate::model::TurnRun::MAX_MODEL_LEN as i32),
        )
        .check(Expr::col(TurnRun::AgentRunDepth).eq(0))
        .check(valid_turn_status)
        .check(
            Expr::col(TurnRun::AttemptCount)
                .gte(0)
                .and(Expr::col(TurnRun::MaxAttempts).gte(1))
                .and(Expr::col(TurnRun::AttemptCount).lte(Expr::col(TurnRun::MaxAttempts))),
        )
        .check(Expr::col(TurnRun::ClaimCount).gte(Expr::col(TurnRun::AttemptCount)))
        .check(active_lease.or(no_lease))
        .check(turn_run_terminal_output_check())
        .check(terminal_finished.or(nonterminal_unfinished))
        .check(
            queued_attempt
                .or(leased_attempt)
                .or(continuation_checkpoint_attempt)
                .or(retryable_attempt)
                .or(resolved_attempt)
                .or(cancelled_attempt),
        )
        .check(failure_has_error.or(success_has_no_error))
        .check(
            Expr::col(TurnRun::LastErrorCode)
                .is_null()
                .or(Func::char_length(Expr::col(TurnRun::LastErrorCode))
                    .between(1, crate::model::TurnRun::MAX_ERROR_CODE_LEN as i32)),
        )
        .check(
            Expr::col(TurnRun::LastErrorDetail)
                .is_null()
                .or(Func::char_length(Expr::col(TurnRun::LastErrorDetail))
                    .between(1, crate::model::TurnRun::MAX_ERROR_DETAIL_LEN as i32)),
        )
        .check(Expr::col(TurnRun::SteerRevision).gte(0))
        .check(coherent_steer_generation)
        .check(
            Expr::col(TurnRun::ModelSteps)
                .gte(0)
                .and(Expr::col(TurnRun::ModelSteps).lte(i64::from(i32::MAX)))
                .and(Expr::col(TurnRun::InputTokens).gte(0))
                .and(Expr::col(TurnRun::InputTokens).lte(i64::from(u32::MAX)))
                .and(Expr::col(TurnRun::OutputTokens).gte(0))
                .and(Expr::col(TurnRun::OutputTokens).lte(i64::from(u32::MAX)))
                .and(Expr::col(TurnRun::CacheReadInputTokens).gte(0))
                .and(Expr::col(TurnRun::CacheReadInputTokens).lte(i64::from(u32::MAX)))
                .and(Expr::col(TurnRun::CacheCreationInputTokens).gte(0))
                .and(Expr::col(TurnRun::CacheCreationInputTokens).lte(i64::from(u32::MAX))),
        )
        .check(
            Expr::col(TurnRun::LastSteerAppliedAt)
                .is_null()
                .or(Expr::col(TurnRun::LastSteerAppliedAt)
                    .gte(Expr::col(TurnRun::CreatedAt))
                    .and(
                        Expr::col(TurnRun::LastSteerAppliedAt).lte(Expr::col(TurnRun::UpdatedAt)),
                    )),
        )
        .to_owned()
}

/// The terminal-output domain of `turn_run`. Only a completed turn must carry
/// an output message; a cancelled turn may also carry one — the partial prose
/// it had already streamed — or none, when the cancel arrived before any text.
fn turn_run_terminal_output_check() -> SimpleExpr {
    Expr::col(TurnRun::Status)
        .eq(TurnRunStatus::Completed.as_str())
        .and(Expr::col(TurnRun::OutputMessageId).is_not_null())
        .or(Expr::col(TurnRun::Status).eq(TurnRunStatus::Cancelled.as_str()))
        .or(Expr::col(TurnRun::Status)
            .is_not_in([
                TurnRunStatus::Completed.as_str(),
                TurnRunStatus::Cancelled.as_str(),
            ])
            .and(Expr::col(TurnRun::OutputMessageId).is_null()))
}

pub(super) fn turn_run_indexes() -> Vec<IndexCreateStatement> {
    vec![
        Index::create()
            .name("idx_turn_run_chat_identity")
            .table(TurnRun::Table)
            .col(TurnRun::ChatId)
            .col(TurnRun::Id)
            .unique()
            .to_owned(),
        Index::create()
            .name("idx_turn_run_input_message")
            .table(TurnRun::Table)
            .col(TurnRun::InputMessageId)
            .unique()
            .to_owned(),
        Index::create()
            .name("idx_turn_run_one_active")
            .table(TurnRun::Table)
            .col(TurnRun::ChatId)
            .unique()
            .and_where(Expr::col(TurnRun::Status).is_in([
                TurnRunStatus::Queued.as_str(),
                TurnRunStatus::Running.as_str(),
                TurnRunStatus::Cancelling.as_str(),
                TurnRunStatus::WaitingForClient.as_str(),
                TurnRunStatus::WaitingForAgentRun.as_str(),
                TurnRunStatus::CancellingClient.as_str(),
                TurnRunStatus::Resuming.as_str(),
                TurnRunStatus::RetryWait.as_str(),
            ]))
            .to_owned(),
        Index::create()
            .name("idx_turn_run_due")
            .table(TurnRun::Table)
            .col(TurnRun::Status)
            .col(TurnRun::AvailableAt)
            .col(TurnRun::CreatedAt)
            .to_owned(),
        Index::create()
            .name("idx_turn_run_lease_token")
            .table(TurnRun::Table)
            .col(TurnRun::LeaseToken)
            .unique()
            .to_owned(),
        Index::create()
            .name("idx_turn_run_stale_lease")
            .table(TurnRun::Table)
            .col(TurnRun::Status)
            .col(TurnRun::LeaseExpiresAt)
            .to_owned(),
        Index::create()
            .name("idx_turn_run_history")
            .table(TurnRun::Table)
            .col(TurnRun::ChatId)
            .col(TurnRun::CreatedAt)
            .to_owned(),
        Index::create()
            .name("idx_turn_run_admission_owner")
            .table(TurnRun::Table)
            .col(TurnRun::Id)
            .col(TurnRun::ChatId)
            .col(TurnRun::AgentRunId)
            .unique()
            .to_owned(),
    ]
}

pub(super) fn turn_failure_table() -> TableCreateStatement {
    Table::create()
        .table(TurnFailure::Table)
        .col(
            ColumnDef::new(TurnFailure::LeaseToken)
                .uuid()
                .not_null()
                .primary_key(),
        )
        .col(ColumnDef::new(TurnFailure::TurnId).uuid().not_null())
        .col(
            ColumnDef::new(TurnFailure::AttemptCount)
                .integer()
                .not_null(),
        )
        .col(ColumnDef::new(TurnFailure::ModelSteps).integer().not_null())
        .col(
            ColumnDef::new(TurnFailure::InputTokens)
                .big_integer()
                .not_null(),
        )
        .col(
            ColumnDef::new(TurnFailure::OutputTokens)
                .big_integer()
                .not_null(),
        )
        .col(
            ColumnDef::new(TurnFailure::CacheReadInputTokens)
                .big_integer()
                .not_null(),
        )
        .col(
            ColumnDef::new(TurnFailure::CacheCreationInputTokens)
                .big_integer()
                .not_null(),
        )
        .col(ColumnDef::new(TurnFailure::RequestedRetryAt).timestamp_with_time_zone())
        .col(
            ColumnDef::new(TurnFailure::ErrorCode)
                .string_len(crate::model::TurnRun::MAX_ERROR_CODE_LEN as u32)
                .not_null(),
        )
        .col(
            ColumnDef::new(TurnFailure::ErrorDetail)
                .string_len(crate::model::TurnRun::MAX_ERROR_DETAIL_LEN as u32),
        )
        .col(
            ColumnDef::new(TurnFailure::ResolvedAt)
                .timestamp_with_time_zone()
                .not_null(),
        )
        .col(
            ColumnDef::new(TurnFailure::ResultStatus)
                .string_len(32)
                .not_null(),
        )
        .foreign_key(
            ForeignKey::create()
                .name("fk_turn_failure_claim")
                .from_tbl(TurnFailure::Table)
                .from_col(TurnFailure::LeaseToken)
                .from_col(TurnFailure::TurnId)
                .from_col(TurnFailure::AttemptCount)
                .to_tbl(TurnClaim::Table)
                .to_col(TurnClaim::Token)
                .to_col(TurnClaim::TurnId)
                .to_col(TurnClaim::AttemptCount)
                .on_delete(ForeignKeyAction::Restrict),
        )
        .check(Expr::col(TurnFailure::AttemptCount).gte(1))
        .check(Expr::col(TurnFailure::ModelSteps).gte(0))
        .check(Expr::col(TurnFailure::ModelSteps).lte(i32::MAX))
        .check(Expr::col(TurnFailure::InputTokens).gte(0))
        .check(Expr::col(TurnFailure::OutputTokens).gte(0))
        .check(Expr::col(TurnFailure::CacheReadInputTokens).gte(0))
        .check(Expr::col(TurnFailure::CacheCreationInputTokens).gte(0))
        .check(Expr::col(TurnFailure::InputTokens).lte(i64::from(u32::MAX)))
        .check(Expr::col(TurnFailure::OutputTokens).lte(i64::from(u32::MAX)))
        .check(Expr::col(TurnFailure::CacheReadInputTokens).lte(i64::from(u32::MAX)))
        .check(Expr::col(TurnFailure::CacheCreationInputTokens).lte(i64::from(u32::MAX)))
        .check(Expr::col(TurnFailure::ResultStatus).is_in([
            TurnRunStatus::RetryWait.as_str(),
            TurnRunStatus::Failed.as_str(),
        ]))
        .check(
            Expr::col(TurnFailure::ResultStatus)
                .ne(TurnRunStatus::RetryWait.as_str())
                .or(Expr::col(TurnFailure::RequestedRetryAt).is_not_null()),
        )
        .check(
            Expr::col(TurnFailure::RequestedRetryAt)
                .is_null()
                .or(Expr::col(TurnFailure::RequestedRetryAt)
                    .gt(Expr::col(TurnFailure::ResolvedAt))),
        )
        .check(
            Func::char_length(Expr::col(TurnFailure::ErrorCode))
                .between(1, crate::model::TurnRun::MAX_ERROR_CODE_LEN as i32),
        )
        .check(
            Expr::col(TurnFailure::ErrorDetail)
                .is_null()
                .or(Func::char_length(Expr::col(TurnFailure::ErrorDetail))
                    .between(1, crate::model::TurnRun::MAX_ERROR_DETAIL_LEN as i32)),
        )
        .to_owned()
}

pub(super) fn turn_failure_indexes() -> Vec<IndexCreateStatement> {
    vec![]
}

pub(super) fn turn_steer_table() -> TableCreateStatement {
    let pending_steer = Expr::col(TurnSteer::Status)
        .eq(TurnSteerStatus::Pending.as_str())
        .and(Expr::col(TurnSteer::AppliedLeaseToken).is_null())
        .and(Expr::col(TurnSteer::MessageId).is_null())
        .and(Expr::col(TurnSteer::PrecedingAssistantMessageId).is_null())
        .and(Expr::col(TurnSteer::ResolvedAt).is_null());
    let applied_steer = Expr::col(TurnSteer::Status)
        .eq(TurnSteerStatus::Applied.as_str())
        .and(Expr::col(TurnSteer::AppliedLeaseToken).is_not_null())
        .and(Expr::col(TurnSteer::MessageId).is_not_null())
        .and(Expr::col(TurnSteer::ResolvedAt).is_not_null());
    let rejected_steer = Expr::col(TurnSteer::Status)
        .eq(TurnSteerStatus::Rejected.as_str())
        .and(Expr::col(TurnSteer::AppliedLeaseToken).is_null())
        .and(Expr::col(TurnSteer::MessageId).is_null())
        .and(Expr::col(TurnSteer::PrecedingAssistantMessageId).is_null())
        .and(Expr::col(TurnSteer::ResolvedAt).is_not_null());

    Table::create()
        .table(TurnSteer::Table)
        .col(
            ColumnDef::new(TurnSteer::Id)
                .uuid()
                .not_null()
                .primary_key(),
        )
        .col(ColumnDef::new(TurnSteer::TurnId).uuid().not_null())
        .col(ColumnDef::new(TurnSteer::ChatId).uuid().not_null())
        .col(ColumnDef::new(TurnSteer::Content).text().not_null())
        // The skills the user named for this steer, as a JSON array of slugs.
        // Scoped to the one instruction the same way the turn's own list is
        // scoped to its opening message: invocation is a per-message directive,
        // so a steer neither inherits nor extends the turn's list.
        .col(
            ColumnDef::new(TurnSteer::InvokedSkills)
                .json_binary()
                .not_null(),
        )
        .col(
            ColumnDef::new(TurnSteer::VoiceInputUsed)
                .boolean()
                .not_null()
                .default(false),
        )
        .col(
            ColumnDef::new(TurnSteer::Interrupt)
                .boolean()
                .not_null()
                .default(false),
        )
        .col(
            ColumnDef::new(TurnSteer::Status)
                .string_len(16)
                .not_null()
                .default(TurnSteerStatus::Pending.as_str()),
        )
        .col(ColumnDef::new(TurnSteer::AppliedLeaseToken).uuid())
        .col(ColumnDef::new(TurnSteer::MessageId).uuid())
        .col(ColumnDef::new(TurnSteer::PrecedingAssistantMessageId).uuid())
        .col(
            ColumnDef::new(TurnSteer::CreatedAt)
                .timestamp_with_time_zone()
                .not_null(),
        )
        .col(ColumnDef::new(TurnSteer::ResolvedAt).timestamp_with_time_zone())
        .foreign_key(
            ForeignKey::create()
                .name("fk_turn_steer_turn")
                .from_tbl(TurnSteer::Table)
                .from_col(TurnSteer::ChatId)
                .from_col(TurnSteer::TurnId)
                .to_tbl(TurnRun::Table)
                .to_col(TurnRun::ChatId)
                .to_col(TurnRun::Id)
                .on_delete(ForeignKeyAction::Cascade),
        )
        .foreign_key(
            ForeignKey::create()
                .name("fk_turn_steer_preceding_assistant")
                .from_tbl(TurnSteer::Table)
                .from_col(TurnSteer::PrecedingAssistantMessageId)
                .from_col(TurnSteer::ChatId)
                .from_col(TurnSteer::TurnId)
                .to_tbl(Message::Table)
                .to_col(Message::Id)
                .to_col(Message::ChatId)
                .to_col(Message::TurnId)
                .on_delete(ForeignKeyAction::Restrict),
        )
        .foreign_key(
            ForeignKey::create()
                .name("fk_turn_steer_claim")
                .from_tbl(TurnSteer::Table)
                .from_col(TurnSteer::AppliedLeaseToken)
                .from_col(TurnSteer::TurnId)
                .to_tbl(TurnClaim::Table)
                .to_col(TurnClaim::Token)
                .to_col(TurnClaim::TurnId)
                .on_delete(ForeignKeyAction::Restrict),
        )
        .foreign_key(
            ForeignKey::create()
                .name("fk_turn_steer_message")
                .from_tbl(TurnSteer::Table)
                .from_col(TurnSteer::MessageId)
                .from_col(TurnSteer::ChatId)
                .from_col(TurnSteer::TurnId)
                .to_tbl(Message::Table)
                .to_col(Message::Id)
                .to_col(Message::ChatId)
                .to_col(Message::TurnId)
                .on_delete(ForeignKeyAction::Restrict),
        )
        .check(
            Func::char_length(Expr::col(TurnSteer::Content))
                .between(1, crate::model::TurnSteer::MAX_CONTENT_LEN as i32),
        )
        .check(pending_steer.or(applied_steer).or(rejected_steer))
        .check(
            Expr::col(TurnSteer::MessageId)
                .is_null()
                .or(Expr::col(TurnSteer::MessageId).eq(Expr::col(TurnSteer::Id))),
        )
        .check(
            Expr::col(TurnSteer::ResolvedAt)
                .is_null()
                .or(Expr::col(TurnSteer::ResolvedAt).gte(Expr::col(TurnSteer::CreatedAt))),
        )
        .to_owned()
}

pub(super) fn turn_steer_indexes() -> Vec<IndexCreateStatement> {
    vec![
        Index::create()
            .name("idx_turn_steer_pending")
            .table(TurnSteer::Table)
            .col(TurnSteer::TurnId)
            .col(TurnSteer::Status)
            .col(TurnSteer::CreatedAt)
            .col(TurnSteer::Id)
            .to_owned(),
        Index::create()
            .name("idx_turn_steer_message")
            .table(TurnSteer::Table)
            .col(TurnSteer::MessageId)
            .unique()
            .to_owned(),
    ]
}

pub(super) fn turn_client_wait_table() -> TableCreateStatement {
    Table::create()
        .table(TurnClientWait::Table)
        .col(
            ColumnDef::new(TurnClientWait::CallId)
                .uuid()
                .not_null()
                .primary_key(),
        )
        .col(ColumnDef::new(TurnClientWait::TurnId).uuid().not_null())
        .col(ColumnDef::new(TurnClientWait::ChatId).uuid().not_null())
        .col(
            ColumnDef::new(TurnClientWait::ParkLeaseToken)
                .uuid()
                .not_null(),
        )
        .col(
            ColumnDef::new(TurnClientWait::AttemptCount)
                .integer()
                .not_null(),
        )
        .col(
            ColumnDef::new(TurnClientWait::ClaimCount)
                .integer()
                .not_null(),
        )
        .col(
            ColumnDef::new(TurnClientWait::ModelSteps)
                .integer()
                .not_null(),
        )
        .col(
            ColumnDef::new(TurnClientWait::InputTokens)
                .big_integer()
                .not_null(),
        )
        .col(
            ColumnDef::new(TurnClientWait::OutputTokens)
                .big_integer()
                .not_null(),
        )
        .col(
            ColumnDef::new(TurnClientWait::CacheReadInputTokens)
                .big_integer()
                .not_null(),
        )
        .col(
            ColumnDef::new(TurnClientWait::CacheCreationInputTokens)
                .big_integer()
                .not_null(),
        )
        .col(ColumnDef::new(TurnClientWait::Status).text().not_null())
        .col(
            ColumnDef::new(TurnClientWait::ParkedAt)
                .timestamp_with_time_zone()
                .not_null(),
        )
        .col(ColumnDef::new(TurnClientWait::ClosedAt).timestamp_with_time_zone())
        .foreign_key(
            ForeignKey::create()
                .name("fk_turn_client_wait_call")
                .from_tbl(TurnClientWait::Table)
                .from_col(TurnClientWait::CallId)
                .from_col(TurnClientWait::ChatId)
                .from_col(TurnClientWait::TurnId)
                .to_tbl(ToolCall::Table)
                .to_col(ToolCall::Id)
                .to_col(ToolCall::ChatId)
                .to_col(ToolCall::TurnId)
                .on_delete(ForeignKeyAction::Restrict),
        )
        .foreign_key(
            ForeignKey::create()
                .name("fk_turn_client_wait_claim")
                .from_tbl(TurnClientWait::Table)
                .from_col(TurnClientWait::ParkLeaseToken)
                .from_col(TurnClientWait::TurnId)
                .from_col(TurnClientWait::AttemptCount)
                .from_col(TurnClientWait::ClaimCount)
                .to_tbl(TurnClaim::Table)
                .to_col(TurnClaim::Token)
                .to_col(TurnClaim::TurnId)
                .to_col(TurnClaim::AttemptCount)
                .to_col(TurnClaim::ClaimCount)
                .on_delete(ForeignKeyAction::Restrict),
        )
        .check(Expr::col(TurnClientWait::Status).is_in([
            TurnClientWaitStatus::Waiting.as_str(),
            TurnClientWaitStatus::Resumed.as_str(),
            TurnClientWaitStatus::Cancelled.as_str(),
        ]))
        .check(
            Expr::col(TurnClientWait::Status)
                .eq(TurnClientWaitStatus::Waiting.as_str())
                .and(Expr::col(TurnClientWait::ClosedAt).is_null())
                .or(Expr::col(TurnClientWait::Status)
                    .ne(TurnClientWaitStatus::Waiting.as_str())
                    .and(Expr::col(TurnClientWait::ClosedAt).is_not_null())),
        )
        .check(
            Expr::col(TurnClientWait::ClosedAt)
                .is_null()
                .or(Expr::col(TurnClientWait::ClosedAt).gte(Expr::col(TurnClientWait::ParkedAt))),
        )
        .check(
            Expr::col(TurnClientWait::ModelSteps)
                .gt(0)
                .and(Expr::col(TurnClientWait::ModelSteps).lte(i64::from(i32::MAX)))
                .and(Expr::col(TurnClientWait::InputTokens).gte(0))
                .and(Expr::col(TurnClientWait::InputTokens).lte(i64::from(u32::MAX)))
                .and(Expr::col(TurnClientWait::OutputTokens).gte(0))
                .and(Expr::col(TurnClientWait::OutputTokens).lte(i64::from(u32::MAX)))
                .and(Expr::col(TurnClientWait::CacheReadInputTokens).gte(0))
                .and(Expr::col(TurnClientWait::CacheReadInputTokens).lte(i64::from(u32::MAX)))
                .and(Expr::col(TurnClientWait::CacheCreationInputTokens).gte(0))
                .and(Expr::col(TurnClientWait::CacheCreationInputTokens).lte(i64::from(u32::MAX))),
        )
        .to_owned()
}

pub(super) fn turn_client_wait_indexes() -> Vec<IndexCreateStatement> {
    vec![
        Index::create()
            .name("idx_turn_client_wait_one_open")
            .table(TurnClientWait::Table)
            .col(TurnClientWait::TurnId)
            .unique()
            .and_where(Expr::col(TurnClientWait::Status).eq(TurnClientWaitStatus::Waiting.as_str()))
            .to_owned(),
        Index::create()
            .name("idx_turn_client_wait_history")
            .table(TurnClientWait::Table)
            .col(TurnClientWait::TurnId)
            .col(TurnClientWait::ParkedAt)
            .col(TurnClientWait::CallId)
            .to_owned(),
    ]
}

pub(super) fn context_checkpoint_table() -> TableCreateStatement {
    Table::create()
        .table(ContextCheckpoint::Table)
        .col(
            ColumnDef::new(ContextCheckpoint::ChatId)
                .uuid()
                .not_null()
                .primary_key(),
        )
        .col(
            ColumnDef::new(ContextCheckpoint::SourceMessageId)
                .uuid()
                .not_null(),
        )
        .col(
            ColumnDef::new(ContextCheckpoint::SourceMessageSeq)
                .big_integer()
                .not_null(),
        )
        .col(
            ColumnDef::new(ContextCheckpoint::FormatVersion)
                .integer()
                .not_null(),
        )
        .col(
            ColumnDef::new(ContextCheckpoint::Content)
                .string_len(crate::semantic_checkpoint::MAX_CONTEXT_CHECKPOINT_BYTES as u32)
                .not_null(),
        )
        .col(
            ColumnDef::new(ContextCheckpoint::CreatedAt)
                .timestamp_with_time_zone()
                .not_null(),
        )
        // Maintenance-model usage, kept out of foreground turn accounting.
        .col(
            ColumnDef::new(ContextCheckpoint::InputTokens)
                .big_integer()
                .not_null()
                .default(0),
        )
        .col(
            ColumnDef::new(ContextCheckpoint::OutputTokens)
                .big_integer()
                .not_null()
                .default(0),
        )
        .col(
            ColumnDef::new(ContextCheckpoint::CacheReadInputTokens)
                .big_integer()
                .not_null()
                .default(0),
        )
        .col(
            ColumnDef::new(ContextCheckpoint::CacheCreationInputTokens)
                .big_integer()
                .not_null()
                .default(0),
        )
        .foreign_key(
            ForeignKey::create()
                .name("fk_context_checkpoint_chat")
                .from(ContextCheckpoint::Table, ContextCheckpoint::ChatId)
                .to(Chat::Table, Chat::Id)
                .on_delete(ForeignKeyAction::Cascade),
        )
        .foreign_key(
            ForeignKey::create()
                .name("fk_context_checkpoint_source_message")
                .from(ContextCheckpoint::Table, ContextCheckpoint::SourceMessageId)
                .to(Message::Table, Message::Id)
                .on_delete(ForeignKeyAction::Restrict),
        )
        .check(Expr::col(ContextCheckpoint::SourceMessageSeq).gt(0))
        .check(Expr::col(ContextCheckpoint::FormatVersion).is_in([
            crate::semantic_checkpoint::CONTEXT_CHECKPOINT_FORMAT_V1 as i32,
            crate::semantic_checkpoint::CONTEXT_CHECKPOINT_FORMAT_V2 as i32,
        ]))
        .to_owned()
}

pub(super) fn context_checkpoint_indexes() -> Vec<IndexCreateStatement> {
    vec![]
}

/// Global ownership and bounded recovery for one client-supplied turn id.
pub(super) fn turn_admission_table() -> TableCreateStatement {
    Table::create()
        .table(TurnAdmission::Table)
        .col(
            ColumnDef::new(TurnAdmission::Id)
                .uuid()
                .not_null()
                .primary_key(),
        )
        .col(ColumnDef::new(TurnAdmission::ChatId).uuid().not_null())
        .col(
            ColumnDef::new(TurnAdmission::Fingerprint)
                .binary()
                .not_null(),
        )
        .col(
            ColumnDef::new(TurnAdmission::State)
                .string_len(16)
                .not_null(),
        )
        .col(ColumnDef::new(TurnAdmission::LeaseToken).uuid())
        .col(ColumnDef::new(TurnAdmission::LeaseExpiresAt).timestamp_with_time_zone())
        .col(
            ColumnDef::new(TurnAdmission::CreatedAt)
                .timestamp_with_time_zone()
                .not_null(),
        )
        .col(
            ColumnDef::new(TurnAdmission::UpdatedAt)
                .timestamp_with_time_zone()
                .not_null(),
        )
        .foreign_key(
            ForeignKey::create()
                .name("fk_turn_admission_chat")
                .from(TurnAdmission::Table, TurnAdmission::ChatId)
                .to(Chat::Table, Chat::Id)
                .on_delete(ForeignKeyAction::Cascade),
        )
        .check(Expr::col(TurnAdmission::State).is_in(["pending", "queued", "accepted"]))
        .check(
            Expr::col(TurnAdmission::State)
                .eq("pending")
                .and(Expr::col(TurnAdmission::LeaseToken).is_not_null())
                .and(Expr::col(TurnAdmission::LeaseExpiresAt).is_not_null())
                .or(Expr::col(TurnAdmission::State)
                    .ne("pending")
                    .and(Expr::col(TurnAdmission::LeaseToken).is_null())
                    .and(Expr::col(TurnAdmission::LeaseExpiresAt).is_null())),
        )
        .to_owned()
}

pub(super) fn turn_admission_indexes() -> Vec<IndexCreateStatement> {
    vec![Index::create()
        .name("ix_turn_admission_pending_expiry")
        .table(TurnAdmission::Table)
        .col(TurnAdmission::State)
        .col(TurnAdmission::LeaseExpiresAt)
        .to_owned()]
}

/// Messages waiting to become turns, FIFO per chat.
pub(super) fn queued_turn_table() -> TableCreateStatement {
    Table::create()
        .table(QueuedTurn::Table)
        .col(
            ColumnDef::new(QueuedTurn::Id)
                .uuid()
                .not_null()
                .primary_key(),
        )
        .col(ColumnDef::new(QueuedTurn::ChatId).uuid().not_null())
        .col(ColumnDef::new(QueuedTurn::Content).text().not_null())
        .col(
            ColumnDef::new(QueuedTurn::AttachmentsJson)
                .text()
                .not_null()
                .default("[]"),
        )
        .col(
            ColumnDef::new(QueuedTurn::FileAttachmentsJson)
                .text()
                .not_null()
                .default("[]"),
        )
        .col(
            ColumnDef::new(QueuedTurn::InvokedSkillsJson)
                .text()
                .not_null()
                .default("[]"),
        )
        .col(
            ColumnDef::new(QueuedTurn::VoiceInputUsed)
                .boolean()
                .not_null()
                .default(false),
        )
        .col(ColumnDef::new(QueuedTurn::Position).integer().not_null())
        .col(
            ColumnDef::new(QueuedTurn::CreatedAt)
                .timestamp_with_time_zone()
                .not_null(),
        )
        .col(
            ColumnDef::new(QueuedTurn::UpdatedAt)
                .timestamp_with_time_zone()
                .not_null(),
        )
        .foreign_key(
            ForeignKey::create()
                .name("fk_queued_turn_chat")
                .from(QueuedTurn::Table, QueuedTurn::ChatId)
                .to(Chat::Table, Chat::Id)
                .on_delete(ForeignKeyAction::Cascade),
        )
        .check(Func::char_length(Expr::col(QueuedTurn::Content)).gt(0))
        .check(Expr::col(QueuedTurn::Position).gte(0))
        .to_owned()
}

pub(super) fn queued_turn_indexes() -> Vec<IndexCreateStatement> {
    vec![Index::create()
        .name("ix_queued_turn_chat_position")
        .table(QueuedTurn::Table)
        .col(QueuedTurn::ChatId)
        .col(QueuedTurn::Position)
        .to_owned()]
}
